### ISSUE TITLE
Is there a way to create a database from a folder of csv files?

### ISSUE THREAD

**Issue by dmadeka** [hannesmuehleisen/MonetDBLite-Python#10]
Similar to the R command - `dbWriteTable`, I'd like to take a folder of large csv files and make a DB out of them

**Comment by hannesmuehleisen** [comment]
Do all the files have the same columns and should go into the same table?

**Comment by hannesmuehleisen** [comment]
There is functionality to support this already:
````
>>> import monetdblite, pandas
>>> monetdblite.init('/tmp/test')
>>> monetdblite.create('test', pandas.read_csv('test.csv').to_dict('series'))
````

With test.csv looking like this

````
a,b
1,2
3,4
5,6
````

So to load an entire directory, you could list the files and then call `.create`.

**Comment by dmadeka** [comment]
@hannesmuehleisen All the csvs look the same - I was more wondering if this read the csvs in parallel, or I needed to use something like Dask

**Comment by hannesmuehleisen** [comment]
You could run a thread per file, load them into separate tables, and create a `VIEW` over them in the end for example?
