### ISSUE TITLE
Testing on OSX and Windows

### ISSUE THREAD

**Issue by hannesmuehleisen** [hannesmuehleisen/MonetDBLite-Python#18]
Travis should be extended to also test on OSX
Appveyor should be using a working compiler, probably MinGW?

**Comment by hannesmuehleisen** [comment]
I added this for testing purposes https://raw.githubusercontent.com/pypa/python-packaging-user-guide/master/source/guides/appveyor-sample/appveyor.yml

**Comment by hannesmuehleisen** [comment]
See also here https://packaging.python.org/guides/supporting-windows-using-appveyor/

**Comment by hannesmuehleisen** [comment]
some movement https://ci.appveyor.com/project/hannesmuehleisen/monetdblite-python/build/1.0.59/job/ye6iugh53e0ydue4

**Comment by hannesmuehleisen** [comment]
https://ci.appveyor.com/project/hannesmuehleisen/monetdblite-python/build/1.0.110

**Comment by hannesmuehleisen** [comment]
@kutsurak , can you perhaps figure out how to add testing for visual studio 2015 and mingw64 32/64 bit versions 6.x? See https://www.appveyor.com/docs/build-environment/ for some info, I think the build image needs to be switched for this. The rest works amazingly!

**Comment by kutsurak** [comment]
Sure I am working on it now.

**Comment by kutsurak** [comment]
This looks promising: https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by kutsurak** [comment]
Actually Appveyor already installs it: https://www.appveyor.com/docs/build-environment/#python. Now to find a way to use it

**Comment by kutsurak** [comment]
Apparently Travis does not support Python on OSX: https://travis-ci.org/kutsurak/MonetDBLite-Python/builds/403468658

**Comment by hannesmuehleisen** [comment]
We could probably hack it by using c env and installing py via brew

**Comment by hannesmuehleisen** [comment]
So travis has announced windows support. perhaps that would simplify matters? https://blog.travis-ci.com/2018-10-11-windows-early-release
