### ISSUE TITLE
connection. set_autocommit(False) fails silently

### ISSUE THREAD

**Issue by gijzelaerr** [hannesmuehleisen/MonetDBLite-Python#2]
https://github.com/hannesmuehleisen/MonetDBLite-Python/blob/master/monetdblite/connections.py#L43

**Comment by hannesmuehleisen** [comment]
is there a spec somewhere how the `set_autocommit` method should behave if there is already an uncommitted transaction running? revert?

**Comment by gijzelaerr** [comment]
I don't think the Python DBAPI covers this. I expect it is valid if the drivers raises an exception.
